language: node_js
node_js:
  - node
  - lts/*
dist: xenial
services:
  - xvfb
before_install:
  - npm install jquery
script:
  - npm run clean
  - npm run build
  - npm run test
branches:
  only:
    - master
addons:
  code_climate:
    repo_token: 83a3827bbb1e879e17dcd945a6cdac0dd0dd0954316b72c471bad34ca19cc84e
